name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-upm:
    name: Deploy to UPM
    runs-on: ubuntu-latest
    env:
        PKG_ROOT: Packages/io.dyrda.singleton-mono-behaviour
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0   
    - name: copy files of th emain branch to temp
      run: |
        mkdir temp
        cp README.md temp/
        cp README.md.meta temp/
        
        cp CHANGELOG.md temp/
        cp CHANGELOG.md.meta temp/
        
        cp LICENSE.md temp/
        cp LICENSE.md.meta temp/
        
        cp ThirdPartyContent.md temp/
        cp ThirdPartyContent.md.meta temp/
    - name: split upm-raw branch
      run: |
        git subtree split -P "$PKG_ROOT" -b upm-raw
        git push -u origin upm-raw
    - name: update upm branch
      run: |
        git fetch
        git push origin --delete upm
        git checkout -b upm upm-raw
        git push origin upm
    - name: overwrite package files with current files from the main branch
      run: |  
        # echo "WHATioo" >> temp/README.md
        cat temp/README.md > README.md
        cat temp/README.md.meta > README.md.meta
        
        cat temp/CHANGELOG.md > CHANGELOG.md
        cat temp/CHANGELOG.md.meta > CHANGELOG.md.meta
        
        cat temp/LICENSE.md > LICENSE.md
        cat temp/LICENSE.md.meta > LICENSE.md.meta
        
        cat temp/ThirdPartyContent.md > ThirdPartyContent.md
        cat temp/ThirdPartyContent.md.meta > ThirdPartyContent.md.meta
    - name: prepare files commit
      run: |
        # Remove temp
        sudo rm -r -f temp/
        # Set necessary information
        git config --local user.email "github-action@dyrda.io" 
        git config --local user.name "github-action"
    - name: optional files commit
      run: |
        git add "README.md"
        git add "README.md.meta" 
        
        git add "CHANGELOG.md"
        git add "CHANGELOG.md.meta"
        
        git add "LICENSE.md"
        git add "LICENSE.md.meta" 
        
        git add "ThirdPartyContent.md"
        git add "ThirdPartyContent.md.meta" 
        
        git commit -m"Automatically copied the original REPO files (README, CHANGELOG, LICENSE and ThirdPartyNotice) to the upm package.";
        # if [[ $(git diff --exit-code README.md) ]]; then
        # git add "README.md" && git commit -m"Automatically copied the original REPO files (README, CHANGELOG, LICENSE and ThirdPartyNotice) to the upm package.";
        # fi
    - name: push upm branch
      run: |  
        git push -u origin upm
